### ISSUE TITLE
Correções do LAB-01

### ISSUE THREAD

**Issue by fsantanna-uerj** [EmersonVargas/LP1#2]
- colocar as respostas em um diretório separado (ex., `lab-01/*`)
- colocar as imagens com a execução dos programas

**Comment by EmersonVargas** [comment]
Ok. 
Já separei os trabalhos separados em pastas.
já coloquei as imagens das execuções dos programas.
Obs.: Executei e obtive imagens dos programas no devC++ pois ainda não tenho linux instalado em meu computador, instalarei posteriormente.

**Comment by fsantanna** [comment]
ok, obrigado.
(Pode fechar essa issue em "Close issue")
