### ISSUE TITLE
PRIMOS: tem como fazer removendo esse contador `cont`

### ISSUE THREAD

**Issue by fsantanna** [EmersonVargas/LP1#3]
https://github.com/EmersonVargas/LP1/blob/fae85e1feb3c07a0a334fdc97ef9c20eac85bf2a/Lab-Primo/primo.c#L7

**Comment by EmersonVargas** [comment]
Corrigido. Utilizei a propria variavel de retorno "primo" como contador. anexei um novo codigo eh_primo2.c com essa correção na pasta.

**Comment by fsantanna** [comment]
A questão não é essa.
Não é necessário contador nenhum.
A partir do momento que você acha um divisor, você já pode retornar 0 imediatamente.
Tem que pensar apenas em como decidir quando ele é primo.
