### ISSUE TITLE
TODOS-PRIMOS: essa linha não está fazendo nada. tirar e testar

### ISSUE THREAD

**Issue by fsantanna** [EmersonVargas/LP1#4]
https://github.com/EmersonVargas/LP1/blob/fae85e1feb3c07a0a334fdc97ef9c20eac85bf2a/Lab-Primo/todosp.c#L21

**Comment by EmersonVargas** [comment]
Corrigido. Eu havia pensado que deveria inicializar a função antes, realmente não tem necessidade pois ela esta sendo iniializada dentro do if, retirei esse trecho dos códigos.

**Comment by fsantanna** [comment]
ok
